apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      dnsConfig:
        nameservers:
          - 1.1.1.1
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
      containers:
        - name: {{ .Chart.Name }}
          image:  {{ .Values.image.repository }}/{{ .Chart.Name }}:{{ .Values.image.tag }}-{{ .Values.image.os | default "linux"}}-{{ .Values.image.arch | default "amd64"}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: 
            - name: {{ .Values.secret.tokenName }}
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.secret.tokenKey }}
                  name: {{ .Values.secret.name }}
